FROM node:20-alpine as base
WORKDIR /app
COPY package.json package-lock.json* .npmrc* ./
RUN npm install --production=false || yarn install || pnpm install
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=base /app .
EXPOSE 3000
CMD ["npm", "start"]
